AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/setup'
  RunRailsCops: true

Metrics/LineLength:
  Exclude:
    - Gemfile
    - Rakefile
    - Procfile

Style/Documentation:
  Exclude:
    - app/controllers/application_controller.rb
    - app/helpers/application_helper.rb
    - app/controllers/concerns/authenticatable.rb

Style/ClassAndModuleChildren:
  Enabled: false
