Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingComma:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

Style/Documentation:
  Exclude:
    - app/controllers/application_controller.rb
    - app/helpers/application_helper.rb
    - app/controllers/concerns/authenticatable.rb
